title: CODE - a blog by Berry de Jager
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
permalink: ':title/'
baseurl: "" # the subpath of your site, e.g. /blog
url: "code.berrydejager.com" # the base hostname & protocol for your site, e.g. http://example.com
site-twitter: berrydejager #if your site has a twitter account, enter it here

# Author Settings
author: Berry de Jager # add your name
author-img: berry-de-jager.jpg # add your photo
about-author: Enthralled by code since the arrival of the 8-bit cpu. # add description
social-twitter: berrydejager # add your Twitter handle
social-facebook: berrydejagercom # add your Facebook handle
social-github: berrydejager # add your Github handle
social-linkedin: berrydejager.com # add your Linkedin handle
social-email: code@berrydejager.com # add your Email address

# Disqus
discus-identifier: code-berrydejager-com # add your discus identifier

# Tracker
analytics: UA-190232947-1  # Google Analytics

# Build Settings
markdown: kramdown
plugins:
  - jekyll-sitemap
  - jekyll-paginate
  - jemoji

paginate: 32
paginate_path: "/page/:num"

exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock"]
